version: "3.9"

services:
  backend:
    build: .
    container_name: trading_backend
    expose:
      - "5000"
    environment:
      - VIRTUAL_HOST=trade.yourdomain.com
      - VIRTUAL_PATH=/api
      - LETSENCRYPT_HOST=trade.yourdomain.com
      - LETSENCRYPT_EMAIL=your@email.com
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: trading_frontend
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=trade.yourdomain.com
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=trade.yourdomain.com
      - LETSENCRYPT_EMAIL=your@email.com
    depends_on:
      - backend
    restart: unless-stopped

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-custom.conf:/etc/nginx/conf.d/custom.conf:ro
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_ssl
    environment:
      - NGINX_PROXY_CONTAINER=nginx_proxy
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    restart: unless-stopped